version: "3.6"
services:
  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${POSTGRES_USER-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-postgres}
      - POSTGRES_DB=${POSTGRES_DB-db}
    restart: on-failure
    ports:
      - "5432:5432"

  db-admin:
    image: dbeaver/cloudbeaver:latest
    restart: always
    ports:
     - "8080:8978"
    profiles:
     - debug

volumes:
  db-data:
